### PR TITLE
Add support for milliseconds as an expirationUnit option

### PR DESCRIPTION
**Pull request by booleanbetrayal**
Might as well ... actually eliminated a bunch of unit test refactoring in another project that would otherwise have to be done. Let me know if you have any questions @ivpusic !

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
Might as well ... actually eliminated a bunch of unit test refactoring in another project that would otherwise have to be done. Let me know if you have any questions @ivpusic !

**Comment by booleanbetrayal** [comment]
Would be great to get a dist build + version bump if this gets merged.  =]

**Comment by booleanbetrayal** [comment]
wondering if you had a chance to look at this yet @ivpusic

**Comment by ivpusic** [comment]
thanks, merged

**Pull request merged**
